# Aula 02

In [4]:
!pip install nltk --trusted-host nexus.petrobras.com.br -i https://nexus.petrobras.com.br/nexus/repository/pypi-all/simple/

Looking in indexes: https://nexus.petrobras.com.br/nexus/repository/pypi-all/simple/


## Revisão sobre Corpus

In [2]:
poema = """E agora, José?
A festa acabou,
a luz apagou,
o povo sumiu,
a noite esfriou,
e agora, José?
e agora, você?
você que é sem nome,
que zomba dos outros,
você que faz versos,
que ama, protesta?
e agora, José?

Está sem mulher,
está sem discurso,
está sem carinho,
já não pode beber,
já não pode fumar,
cuspir já não pode,
a noite esfriou,
o dia não veio,
o bonde não veio,
o riso não veio,
não veio a utopia
e tudo acabou
e tudo fugiu
e tudo mofou,
e agora, José?

E agora, José?
Sua doce palavra,
seu instante de febre,
sua gula e jejum,
sua biblioteca,
sua lavra de ouro,
seu terno de vidro,
sua incoerência,
seu ódio - e agora?

Com a chave na mão
quer abrir a porta,
não existe porta;
quer morrer no mar,
mas o mar secou;
quer ir para Minas,
Minas não há mais.
José, e agora?

Se você gritasse,
se você gemesse,
se você tocasse
a valsa vienense,
se você dormisse,
se você cansasse,
se você morresse...
Mas você não morre,
você é duro, José!

Sozinho no escuro
qual bicho-do-mato,
sem teogonia,
sem parede nua
para se encostar,
sem cavalo preto
que fuja a galope,
você marcha, José!
José, para onde?"""

In [5]:
import nltk
from nltk import tokenize
nltk.download('punkt') # Baixa o tokenizador

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\HR66\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [6]:
# Contagem de tokens e types
tokens = tokenize.word_tokenize(poema, language='portuguese')
minusculas = tokenize.word_tokenize(poema.lower(), language='portuguese')

vocabulario = set(minusculas)

print("Quantidade de tokens:", len(tokens))
print("Quantidade de types:", len(vocabulario))

Quantidade de tokens: 274
Quantidade de types: 109


In [7]:
print(tokens)

['E', 'agora', ',', 'José', '?', 'A', 'festa', 'acabou', ',', 'a', 'luz', 'apagou', ',', 'o', 'povo', 'sumiu', ',', 'a', 'noite', 'esfriou', ',', 'e', 'agora', ',', 'José', '?', 'e', 'agora', ',', 'você', '?', 'você', 'que', 'é', 'sem', 'nome', ',', 'que', 'zomba', 'dos', 'outros', ',', 'você', 'que', 'faz', 'versos', ',', 'que', 'ama', ',', 'protesta', '?', 'e', 'agora', ',', 'José', '?', 'Está', 'sem', 'mulher', ',', 'está', 'sem', 'discurso', ',', 'está', 'sem', 'carinho', ',', 'já', 'não', 'pode', 'beber', ',', 'já', 'não', 'pode', 'fumar', ',', 'cuspir', 'já', 'não', 'pode', ',', 'a', 'noite', 'esfriou', ',', 'o', 'dia', 'não', 'veio', ',', 'o', 'bonde', 'não', 'veio', ',', 'o', 'riso', 'não', 'veio', ',', 'não', 'veio', 'a', 'utopia', 'e', 'tudo', 'acabou', 'e', 'tudo', 'fugiu', 'e', 'tudo', 'mofou', ',', 'e', 'agora', ',', 'José', '?', 'E', 'agora', ',', 'José', '?', 'Sua', 'doce', 'palavra', ',', 'seu', 'instante', 'de', 'febre', ',', 'sua', 'gula', 'e', 'jejum', ',', 'sua', 'b

In [8]:
print(vocabulario)

{'festa', 'biblioteca', 'pode', 'morresse', 'dos', 'mão', 'noite', 'secou', 'e', 'ama', 'beber', 'cavalo', 'fuja', 'mas', 'dormisse', 'com', 'bicho-do-mato', 'luz', 'galope', 'qual', 'nua', 'carinho', 'utopia', 'mofou', 'você', 'quer', 'sem', 'vidro', 'agora', 'há', '?', 'josé', 'tocasse', 'de', 'versos', 'fugiu', 'morrer', 'fumar', 'gritasse', 'mulher', 'vienense', 'parede', 'chave', 'se', '!', '.', 'morre', 'veio', 'protesta', 'está', 'cuspir', 'dia', 'povo', 'mais', 'esfriou', 'valsa', 'outros', 'preto', 'ir', 'sozinho', 'o', '...', 'duro', 'cansasse', 'a', 'nome', 'tudo', 'bonde', ',', 'não', 'escuro', 'existe', 'discurso', 'no', 'marcha', 'seu', 'gula', 'terno', 'incoerência', 'já', 'minas', 'mar', 'palavra', 'sumiu', 'ódio', 'faz', 'febre', 'riso', 'ouro', 'encostar', 'sua', 'apagou', 'porta', 'onde', 'que', '-', 'na', 'para', 'lavra', 'acabou', 'instante', 'é', 'teogonia', 'abrir', 'gemesse', ';', 'jejum', 'zomba', 'doce'}


In [9]:
# Segmentação de sentenças
sentencas = tokenize.sent_tokenize(poema, language='portuguese')
print(sentencas)
print("Quantidade de sentenças:", len(sentencas))

['E agora, José?', 'A festa acabou,\na luz apagou,\no povo sumiu,\na noite esfriou,\ne agora, José?', 'e agora, você?', 'você que é sem nome,\nque zomba dos outros,\nvocê que faz versos,\nque ama, protesta?', 'e agora, José?', 'Está sem mulher,\nestá sem discurso,\nestá sem carinho,\njá não pode beber,\njá não pode fumar,\ncuspir já não pode,\na noite esfriou,\no dia não veio,\no bonde não veio,\no riso não veio,\nnão veio a utopia\ne tudo acabou\ne tudo fugiu\ne tudo mofou,\ne agora, José?', 'E agora, José?', 'Sua doce palavra,\nseu instante de febre,\nsua gula e jejum,\nsua biblioteca,\nsua lavra de ouro,\nseu terno de vidro,\nsua incoerência,\nseu ódio - e agora?', 'Com a chave na mão\nquer abrir a porta,\nnão existe porta;\nquer morrer no mar,\nmas o mar secou;\nquer ir para Minas,\nMinas não há mais.', 'José, e agora?', 'Se você gritasse,\nse você gemesse,\nse você tocasse\na valsa vienense,\nse você dormisse,\nse você cansasse,\nse você morresse...', 'Mas você não morre,\nvocê é 

## Similaridade Textual

In [10]:
import pandas as pd
import numpy as np

In [11]:
texts = ['Goku is a hero in the Dragon Ball since 1989! Goku saved the earth so many times.',
         'The 7 Dragon balls can make wishes come true! Each ball contains his own dragon.',
         'If the wishes are superfluous, the dragon balls will become dark.' ,
         'Seiya is a bronze knight and is one of the main Knights of the Zodiac. He saved Athena several times.',
         "A knight of the zodiac wear a bronze, silver or a gold cloth to protect Athena.",
         'Saint Seiya: Knights of the Zodiac is a Japanese manga in which mystical warriors called the Saints fight wearing sacred cloths.']
classes = ['Dragon Ball', 'Dragon Ball', 'Dragon Ball', 'Cav. Zod.', 'Cav. Zod.', 'Cav. Zod.']

df = pd.DataFrame({'texts': texts, 'classes': classes})
print(df)

                                               texts      classes
0  Goku is a hero in the Dragon Ball since 1989! ...  Dragon Ball
1  The 7 Dragon balls can make wishes come true! ...  Dragon Ball
2  If the wishes are superfluous, the dragon ball...  Dragon Ball
3  Seiya is a bronze knight and is one of the mai...    Cav. Zod.
4  A knight of the zodiac wear a bronze, silver o...    Cav. Zod.
5  Saint Seiya: Knights of the Zodiac is a Japane...    Cav. Zod.


In [18]:
# Similaridade textual baseada em caractéres

# A distância de Levenshtein é uma métrica de dissimilaridade entre duas strings. O valor da distância descreve o número mínimo de edições necessárias para transformar uma string na outra.

def levenshtein(seq1, seq2):
    # criar a matriz:
    size_x = len(seq1) + 1
    size_y = len(seq2) + 1
    matrix = np.zeros ((size_x, size_y))

    # setar número das colunas (0, n-1)
    for x in range(size_x):
        matrix [x, 0] = x
    # setar número das linhas (0, n-1)
    for y in range(size_y):
        matrix [0, y] = y

    # Calcular distância de Levenshtein
    for x in range(1, size_x): # fazer loop de 1 até n
        for y in range(1, size_y): # fazer loop de 1 até n
            if seq1[x-1] == seq2[y-1]: # se os caracteres forem iguais não aumenta a distância
                matrix [x,y] = matrix [x-1, y-1]
            else:
                matrix [x,y] = min(
                    matrix[x-1, y] + 1, # deletar
                    matrix[x-1, y-1] + 1, # substituir
                    matrix[x, y-1] + 1 # inserir
                )
    print(pd.DataFrame(matrix[1:,1:], index=list(seq1), columns=list(seq2)))

    return (matrix[size_x - 1, size_y - 1])

levenshtein('Goku', 'Gohan')
print('\n')
levenshtein('medicina', 'medico')
print('\n')
levenshtein('seiya', 'shiryu')

     G    o    h    a    n
G  0.0  1.0  2.0  3.0  4.0
o  1.0  0.0  1.0  2.0  3.0
k  2.0  1.0  1.0  2.0  3.0
u  3.0  2.0  2.0  2.0  3.0


     m    e    d    i    c    o
m  0.0  1.0  2.0  3.0  4.0  5.0
e  1.0  0.0  1.0  2.0  3.0  4.0
d  2.0  1.0  0.0  1.0  2.0  3.0
i  3.0  2.0  1.0  0.0  1.0  2.0
c  4.0  3.0  2.0  1.0  0.0  1.0
i  5.0  4.0  3.0  2.0  1.0  1.0
n  6.0  5.0  4.0  3.0  2.0  2.0
a  7.0  6.0  5.0  4.0  3.0  3.0


     s    h    i    r    y    u
s  0.0  1.0  2.0  3.0  4.0  5.0
e  1.0  1.0  2.0  3.0  4.0  5.0
i  2.0  2.0  1.0  2.0  3.0  4.0
y  3.0  3.0  2.0  2.0  2.0  3.0
a  4.0  4.0  3.0  3.0  3.0  3.0


3.0

In [20]:
# Comparar sentenças
print(df)
print('\n')
doc_ia_a = 3 
doc_ia_b = 2
print('Texto 1:', df.loc[doc_ia_a, 'texts'])
print('Texto 2:', df.loc[doc_ia_b, 'texts'])
print('\n')

levenshtein(df.loc[doc_ia_a, 'texts'], df.loc[doc_ia_b, 'texts'])

                                               texts      classes
0  Goku is a hero in the Dragon Ball since 1989! ...  Dragon Ball
1  The 7 Dragon balls can make wishes come true! ...  Dragon Ball
2  If the wishes are superfluous, the dragon ball...  Dragon Ball
3  Seiya is a bronze knight and is one of the mai...    Cav. Zod.
4  A knight of the zodiac wear a bronze, silver o...    Cav. Zod.
5  Saint Seiya: Knights of the Zodiac is a Japane...    Cav. Zod.


Texto 1: Seiya is a bronze knight and is one of the main Knights of the Zodiac. He saved Athena several times.
Texto 2: If the wishes are superfluous, the dragon balls will become dark.


        I      f           t     h     e           w     i     s  ...     c  \
S     1.0    2.0   3.0   4.0   5.0   6.0   7.0   8.0   9.0  10.0  ...  56.0   
e     2.0    2.0   3.0   4.0   5.0   5.0   6.0   7.0   8.0   9.0  ...  55.0   
i     3.0    3.0   3.0   4.0   5.0   6.0   6.0   7.0   7.0   8.0  ...  54.0   
y     4.0    4.0   4.0   4.0   5

76.0

In [25]:
# Similaridade textual baseada em termos
from sklearn.feature_extraction.text import CountVectorizer
vetorizador = CountVectorizer(
    lowercase=True, # converte o texto para minúsculo
    stop_words=['is','are','a','or','to','in','the','so','since','many','of'], # remove as stopwords
    min_df=2, # só vai considerar termos que aparecem em pelo menos 2 documentos
    dtype=np.int16 # usa inteiros de 16 bits para economizar memória
)

In [26]:
# obtendo o vocabulário
vetorizador.fit(df['texts'])
print(vetorizador.get_feature_names_out())

['athena' 'ball' 'balls' 'bronze' 'dragon' 'knight' 'knights' 'saved'
 'seiya' 'times' 'wishes' 'zodiac']


In [27]:
# Gerar representação estruturada a partir do vocabulário ajustado
representacao = vetorizador.transform(df['texts'])
# A representação retornada é uma matriz em formato esparso, ou seja, só armazena os valores diferentes de zero
representacao

<6x12 sparse matrix of type '<class 'numpy.int16'>'
	with 26 stored elements in Compressed Sparse Row format>

In [28]:
rep_array = representacao.toarray() # converte a matriz esparsa para um array
print(rep_array)

[[0 1 0 0 1 0 0 1 0 1 0 0]
 [0 1 1 0 2 0 0 0 0 0 1 0]
 [0 0 1 0 1 0 0 0 0 0 1 0]
 [1 0 0 1 0 1 1 1 1 1 0 1]
 [1 0 0 1 0 1 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0 1 0 0 1]]


In [29]:
# Similaridade por Cosseno
from sklearn.metrics.pairwise import cosine_similarity
matrix_sim = cosine_similarity(rep_array)
matrix_sim

array([[1.        , 0.56694671, 0.28867513, 0.35355339, 0.        ,
        0.        ],
       [0.56694671, 1.        , 0.87287156, 0.        , 0.        ,
        0.        ],
       [0.28867513, 0.87287156, 1.        , 0.        , 0.        ,
        0.        ],
       [0.35355339, 0.        , 0.        , 1.        , 0.70710678,
        0.61237244],
       [0.        , 0.        , 0.        , 0.70710678, 1.        ,
        0.28867513],
       [0.        , 0.        , 0.        , 0.61237244, 0.28867513,
        1.        ]])

In [36]:
def most_similar(id_doc, matrix): # buscar texto mais similar
    matrix_sim = cosine_similarity(matrix) # calcular a similaridade
    best_sim = -1 # inicializa a melhor similaridade
    id_best_sim = -1 # inicializa o id do documento mais similar
    for id, doc_sim in enumerate(matrix_sim[id_doc]):
        if id != id_doc:
            if doc_sim > best_sim:
                best_sim = doc_sim
                id_best_sim = id
    return id_best_sim

In [43]:
print(df)
print('\n')
doc_id = 5
print('Texto:', df.loc[doc_id, 'texts'])
print('Texto mais parecido:', df.loc[most_similar(doc_id, rep_array), 'texts'])

                                               texts      classes
0  Goku is a hero in the Dragon Ball since 1989! ...  Dragon Ball
1  The 7 Dragon balls can make wishes come true! ...  Dragon Ball
2  If the wishes are superfluous, the dragon ball...  Dragon Ball
3  Seiya is a bronze knight and is one of the mai...    Cav. Zod.
4  A knight of the zodiac wear a bronze, silver o...    Cav. Zod.
5  Saint Seiya: Knights of the Zodiac is a Japane...    Cav. Zod.


Texto: Saint Seiya: Knights of the Zodiac is a Japanese manga in which mystical warriors called the Saints fight wearing sacred cloths.
Texto mais parecido: Seiya is a bronze knight and is one of the main Knights of the Zodiac. He saved Athena several times.


In [44]:
# Similaridade de Jaccard
# É calculada pela divisão do número de elementos em comum entre dois conjuntos pelo número total de elementos nos conjuntos.
from sklearn.metrics.pairwise import pairwise_distances

def most_similar(id_doc, matrix):
    matrix_sim = 1 - pairwise_distances(matrix, metric='jaccard') # calcular a similaridade
    best_sim = -1 # inicializa a melhor similaridade
    id_best_sim = -1 # inicializa o id do documento mais similar
    for id, doc_sim in enumerate(matrix_sim[id_doc]):
        if id != id_doc:
            if doc_sim > best_sim:
                best_sim = doc_sim
                id_best_sim = id
    return id_best_sim

In [48]:
import warnings
warnings.filterwarnings('ignore')

In [49]:
matrix_sim = 1 - pairwise_distances(rep_array, metric='jaccard')
matrix_sim

array([[1.        , 0.33333333, 0.16666667, 0.2       , 0.        ,
        0.        ],
       [0.33333333, 1.        , 0.75      , 0.        , 0.        ,
        0.        ],
       [0.16666667, 0.75      , 1.        , 0.        , 0.        ,
        0.        ],
       [0.2       , 0.        , 0.        , 1.        , 0.5       ,
        0.375     ],
       [0.        , 0.        , 0.        , 0.5       , 1.        ,
        0.16666667],
       [0.        , 0.        , 0.        , 0.375     , 0.16666667,
        1.        ]])

In [50]:
print(df)
print('\n')
doc_id = 5
print('Texto:', df.loc[doc_id, 'texts'])
print('Texto mais parecido:', df.loc[most_similar(doc_id, rep_array), 'texts'])

                                               texts      classes
0  Goku is a hero in the Dragon Ball since 1989! ...  Dragon Ball
1  The 7 Dragon balls can make wishes come true! ...  Dragon Ball
2  If the wishes are superfluous, the dragon ball...  Dragon Ball
3  Seiya is a bronze knight and is one of the mai...    Cav. Zod.
4  A knight of the zodiac wear a bronze, silver o...    Cav. Zod.
5  Saint Seiya: Knights of the Zodiac is a Japane...    Cav. Zod.


Texto: Saint Seiya: Knights of the Zodiac is a Japanese manga in which mystical warriors called the Saints fight wearing sacred cloths.
Texto mais parecido: Seiya is a bronze knight and is one of the main Knights of the Zodiac. He saved Athena several times.


In [53]:
from sklearn.metrics import jaccard_score
doc_id_a = 5
doc_id_b = 3
texto1 = rep_array[doc_id_a] # representação em termos
texto2 = rep_array[doc_id_b]
print('Texto 1:', rep_array[doc_id_a])
print('Texto 2:', rep_array[doc_id_b])
jaccard_score(texto1, texto2)

Texto 1: [0 0 0 0 0 0 1 0 1 0 0 1]
Texto 2: [1 0 0 1 0 1 1 1 1 1 0 1]


0.375

In [54]:
# Distância Euclidiana
def most_similar(id_doc, matrix):
    matrix_sim = pairwise_distances(matrix, metric='euclidean') # calcular a similaridade
    best_sim = 9999999999
    id_best_sim = -1
    for id, doc_sim in enumerate(matrix_sim[id_doc]):
        if id != id_doc:
            if doc_sim <= best_sim:
                best_sim = doc_sim
                id_best_sim = id
    return id_best_sim

In [55]:
matrix_sim = pairwise_distances(rep_array, metric='euclidean')
matrix_sim

array([[0.        , 2.23606798, 2.23606798, 2.82842712, 2.82842712,
        2.64575131],
       [2.23606798, 0.        , 1.41421356, 3.87298335, 3.31662479,
        3.16227766],
       [2.23606798, 1.41421356, 0.        , 3.31662479, 2.64575131,
        2.44948974],
       [2.82842712, 3.87298335, 3.31662479, 0.        , 2.        ,
        2.23606798],
       [2.82842712, 3.31662479, 2.64575131, 2.        , 0.        ,
        2.23606798],
       [2.64575131, 3.16227766, 2.44948974, 2.23606798, 2.23606798,
        0.        ]])

In [56]:
print(df)
print('\n')
doc_id = 5
print('Texto:', df.loc[doc_id, 'texts'])
print('Texto mais parecido:', df.loc[most_similar(doc_id, rep_array), 'texts'])

                                               texts      classes
0  Goku is a hero in the Dragon Ball since 1989! ...  Dragon Ball
1  The 7 Dragon balls can make wishes come true! ...  Dragon Ball
2  If the wishes are superfluous, the dragon ball...  Dragon Ball
3  Seiya is a bronze knight and is one of the mai...    Cav. Zod.
4  A knight of the zodiac wear a bronze, silver o...    Cav. Zod.
5  Saint Seiya: Knights of the Zodiac is a Japane...    Cav. Zod.


Texto: Saint Seiya: Knights of the Zodiac is a Japanese manga in which mystical warriors called the Saints fight wearing sacred cloths.
Texto mais parecido: A knight of the zodiac wear a bronze, silver or a gold cloth to protect Athena.
